# Generated by Django 4.2.16 on 2024-12-06 02:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(default=user.models.generate_otp, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp_secret',
            field=models.CharField(default=user.models.generate_otp, editable=False, max_length=4),
        ),
    ]
