# Generated by Django 4.2.16 on 2024-12-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
